version: "3.8"
services:
  redis:
    image: "redis:latest"
    container_name: taobin-redis
    hostname: redis_token
    command: ["redis-server", "--include", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "6379:6379"
    volumes:
      - "./redis/data:/var/lib/redis"
      - "./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf"
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - taobin
  database:
      container_name: taobin-database
      image: postgres:14.1-alpine
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      ports:
        - "5432:5432"
      volumes: 
        - "./db:/var/lib/postgresql/data"
      networks:
        - taobin
  service1:
      container_name: taobin-service1
      build: 
          context: .
          dockerfile: ./service1/Dockerfile.local
      volumes: 
          - "./service1:/app/"
      working_dir: /app
      env_file:
          - "./service1/.env"
      ports:
          - "9090:9090"
      networks:
        - taobin
  service2:
      container_name: taobin-service2
      build: 
          context: .
          dockerfile: ./service2/Dockerfile.local
      volumes: 
          - "./service2:/app/"
      working_dir: /app
      env_file:
          - "./service2/.env"
      ports:
          - "9091:9091"
      networks:
        - taobin
networks:
  taobin:
    driver: bridge