### Create Machine
POST http://127.0.0.1:9090/v1/api/machine
Content-Type: application/json

{
    "machine": "Ramkhamhaeng",
    "stock": 100,
    "created_by": "taobin"
}

### Update Machine
PUT http://127.0.0.1:9090/v1/api/machine
Content-Type: application/json

{
    "id": 4,
    "machine": "Ramkhamhaeng",
    "stock": 2,
    "updated_by": "taobin2"
}

### Delete Machine
DELETE http://127.0.0.1:9090/v1/api/machine/1
Content-Type: application/json

{
    "deleted_by": "taobin3"
}

### Get Machine by ID
GET http://127.0.0.1:9090/v1/api/machine/4
Content-Type: application/json

### Query Machine
GET http://127.0.0.1:9090/v1/api/machine
Content-Type: application/json